```{r}
library(tidyverse)
library(here)
library(glue)
library(rlang)
library(mirt)

source(here("02_score_data/02_fit_irt/irt_modular.R"), chdir = TRUE)
source(here("02_score_data/02_fit_irt/registry_helper.R"))
source(here("02_score_data/02_fit_irt/irt_helpers.R"))
```

```{r}
# mods_best <- read_rds(here("02_scoring_outputs/mods_best.rds"))
```

```{r}
# extract scores from all models
mod_scores <- mods_coded |>
  mutate(scores = map(mod_rec, rlevante:::scores)) |>
  select(-mod_rec, -filename, -path, -file, -BIC) |>
  unnest(scores)

# scores_labeled <- mod_scores |>
#   mutate(nfact = nfact |> as_factor() |> fct_recode("1D" = "f1"), #"2D" = "2"),
#          itemtype = itemtype |> as_factor() |>
#            fct_recode("Rasch" = "rasch", "2PL" = "2pl"),
#          invariance = invariance |> fct_recode("none" = ""),
#          metric_type = "ability",
#          model_class = glue("{model_set} ({subset})"),
#          model = glue("{itemtype}-{nfact}-{invariance}")) |>
#   select(item_task = task, run_id, metric_type, metric_value = ability,
#          metric_se = se, nfact, itemtype, invariance, model_class, model)

write_rds(mod_scores, here("02_scoring_outputs/scores/registry_scores.rds"),
          compress = "gz")
```
