```{r load-data}
library(tidyverse)
library(glue)
library(here)
library(redivis)
library(rlevante)

run_data <- read_rds(here(glue("01_fetched_data/run_data.rds")))
participants <- read_rds(here(glue("01_fetched_data/participants.rds")))
trial_data <- read_rds(here(glue("01_fetched_data/trial_data.rds")))
trials_prelim <- read_rds(here(glue("01_fetched_data/trials_prelim.rds")))
```

```{r}
# code various exclusion criteria
runs_coded <- run_data |>
  left_join(participants |> select(user_id, site, dataset), by = "user_id") |>
  relocate(site, dataset, .after = redivis_source) |>
  mutate(language = language |> str_replace("Other\\((.*)\\)", "\\1")) |>
  mutate(validation_msg_run = validation_msg_run |> replace_na("")) |>
  mutate(ex_empty = !(run_id %in% trials_prelim$run_id),
         ex_no_item_uid = !(run_id %in% trial_data$run_id),
         ex_straightlining = str_detect(validation_msg_run, "straightlining"),
         ex_few_trials = str_detect(validation_msg_run, "less_than_10_test_trials"),
         ex_incomplete = !completed,
         ex_buggy = !is.na(task_version) & task_version == "1.0.0-beta.19" &
           task_id %in% c("matrix-reasoning", "mental-rotation", "theory-of-mind")) |>
  mutate(included_1 = !ex_empty & !ex_no_item_uid & !ex_buggy &
           !ex_incomplete & !ex_straightlining & !ex_few_trials)

# for runs not excluded so far, code runs that are duplicates within administration
runs_coded_dup <- runs_coded |>
  filter(included_1) |>
  group_by(user_id, task_id, variant_id, administration_id) |>
  arrange(time_started) |>
  mutate(ex_duplicate = row_number() != 1) |>
  ungroup()

runs_filtered <- runs_coded_dup |> filter(!ex_duplicate)

# subset trials to above runs
trial_data_subset <- trial_data |>
  inner_join(runs_filtered |> select(run_id, task_version, adaptive, language))

# filter out trials with too slow/fast RTs
trial_data_valid <- trial_data_subset |>
  mutate(validation_msg_trial = validation_msg_trial |> replace_na(""),
         slow_rt = rt_numeric > 30000,
         fast_rt = str_detect(validation_msg_trial, "fast")) |>
  filter(task_id == "same-different-selection" | is.na(rt_numeric) | !slow_rt,
         !fast_rt) |>
  select(-slow_rt, -fast_rt, -valid_trial, -validation_msg_trial) |>
  mutate(ex_few_valid_trials = n() < 10, .by = run_id)

# filter out trials from runs that ended with too few valid trials
trial_data_filtered <- trial_data_valid |> filter(!ex_few_valid_trials)

# do various trial-level recoding of items/correctness
trial_data_coded <- trial_data_filtered |>
  left_join(participants |> select(user_id, site, dataset), by = "user_id") |>
  relocate(site, dataset, .after = redivis_source) |>
  rlevante:::recode_trials()

# exclude items that are marked for exclusion
exclusions <- redivis$organization("levante")$dataset("levante_metadata_items:czjv")$table("exclusions:0b5t")$to_tibble()
trial_data_included <- trial_data_coded |> anti_join(exclusions)
```

```{r}
runs_filtered_trials <- runs_filtered |>
  inner_join(trial_data_filtered |> distinct(run_id, ex_few_valid_trials))
write_rds(runs_filtered_trials, here("01_fetched_data/runs_filtered_trials.rds"),
          compress = "gz")

run_exclusions <- runs_coded |>
  select(redivis_source, task_id, run_id, starts_with("ex_")) |>
  left_join(runs_coded_dup |> select(run_id, ex_duplicate)) |>
  left_join(trial_data_valid |> distinct(run_id, ex_few_valid_trials))
write_rds(run_exclusions, here("01_fetched_data/run_exclusions.rds"),
          compress = "gz")
```

```{r}
task_data_nested <- trial_data_included |>
  nest(data = -c(item_task, site, language))

write_rds(task_data_nested, here("01_fetched_data/task_data_nested.rds"),
          compress = "gz")
```
