```{r setup}
library(rlevante)
library(dplyr)
library(here)
library(readr)
library(stringr)
library(tidyr)
```

```{r}
dataset_spec <- list(
  list(name = "pilot_uniandes_co_bogota:3j4z", version = "v7_8"),
  list(name = "pilot_uniandes_co_rural:66d2",  version = "v7_2"),
  list(name = "pilot_mpieva_de_main:6c0n",     version = "v7_4"),
  list(name = "pilot_western_ca_main:97mt",    version = "v7_28"))

runs <- get_runs(dataset_spec,
                 remove_incomplete_runs = FALSE,
                 remove_invalid_runs = FALSE)

run_data <- runs |>
  # filter out CO data post-pilot sample
  filter(!(site == "pilot_uniandes_co" & time_started > ymd_hms("2025-07-01 00:00:00")))

write_rds(run_data, here("01_fetched_data/run_data.rds"), compress = "gz")
```

```{r}
trials_prelim <- get_trials_prelim(dataset_spec,
                                   remove_incomplete_runs = FALSE,
                                   remove_invalid_runs = FALSE,
                                   remove_invalid_trials = FALSE)
write_rds(trials_prelim, here("01_fetched_data/trials_prelim.rds"),
          compress = "gz")

trial_data <- trials_prelim |>
  rlevante:::add_item_ids() |>
  rlevante:::add_item_metadata() |>
  rlevante:::add_trial_numbers() |>
  tidyr::separate_wider_delim(cols = "dataset", delim = ":",
                              names = c("dataset", "ref", "version")) |>
  arrange(.data$dataset, .data$task_id, .data$user_id, .data$run_id, .data$trial_number) |>
  select("redivis_source", "task_id", "user_id", "run_id", "trial_id",
         "trial_number", "item_uid", "item_task", "item_group", "item",
         "correct", "rt", "rt_numeric", "response", "response_type",
         "item_original", "answer", "distractors", "chance", "difficulty",
         "theta_estimate", "theta_se", timestamp = "server_timestamp",
         "valid_trial", "validation_msg_trial")

write_rds(trial_data, here("01_fetched_data/trial_data.rds"), compress = "gz")
```
