```{r load-data}
source(here::here("assessment/colombia/stage2/_setup.R"))

trials_coded <- read_rds(here("assessment/colombia/stage2/data_processed/trials_coded.rds"))
participants <- read_rds(here("assessment/colombia/stage2/data_processed/participants.rds"))
```

Data munging

```{r}
# subtask=="number line?"
score_ntl <- function(item, answer, response, threshold = 0.05) {
  max_value <- as.numeric(str_extract(item, "\\d+(?=\\})"))
  abs(as.numeric(response) - as.numeric(answer)) / max_value < threshold
}

mp <- trials_coded |> filter(task_id == "egma-math") |>
  filter(subtask!="number line slider") 

```

## Subtask Accuracy

```{r, fig.width=7, fig.height=5}
math_ntr <- mp |> group_by(user_id, run_id, age) |>
  summarise(prop_correct = mean(is_correct), n = n()) 

summary(math_ntr$n)


mp |> mutate(subtask = fct_reorder(subtask, trial_index)) |>
  group_by(user_id, run_id, age, subtask) |>
  summarise(prop_correct = mean(is_correct), n = n()) |>
  filter(age<13) |>
  ggplot(aes(x=age, y=prop_correct)) +
    facet_wrap(. ~ subtask) + 
    geom_point(alpha=.3) + 
  geom_smooth() + ylab("Proportion Correct")


mp |> mutate(subtask = fct_reorder(subtask, trial_index)) |>
  group_by(user_id, run_id, age, subtask) |>
  summarise(prop_correct = mean(is_correct), n = n()) |>
  filter(age<13) |>
  ggplot(aes(x=age, y=n)) +
    facet_wrap(. ~ subtask) + 
    geom_point(alpha=.3) + 
  geom_smooth() + ylab("Number of Trials Completed")
```

## IRT Models

```{r}
math_wide <- mp |>
  mutate(is_correct = as.numeric(is_correct),
         item_id = paste(subtask, item, sep='-')) |>
  group_by(user_id, item) |>
  slice(1) |> # some kids have >1 admin??
  select(user_id, item, is_correct) |>
  pivot_wider(names_from = "item", values_from = "is_correct") |>
  ungroup()

math_mat <- as.matrix(select(math_wide, -user_id))
rownames(math_mat) <- math_wide$user_id

# remove columns with no variance
math_cols <- colMeans(math_mat, na.rm=TRUE) 
math_mat <- math_mat[,math_cols > 0 & math_cols < 1]
```

```{r fit-rasch-model}
set.seed(1234)

fit_mirt_math <- function(data_mat, item_type) {
  mod <- mirt(data_mat, itemtype = item_type, verbose = TRUE, guess = .25,
              technical = list(NCYCLES = 1000))
  
  mod_coefs <- coef(mod, simplify = TRUE)$items |> as_tibble(rownames = "item")
  
  scores <- fscores(mod, method = "MAP", verbose = FALSE)
  mod_fscores <- tibble(user_id = rownames(data_mat), ability = scores[,1])
  
  list(model = mod, coefs = mod_coefs, fscores = mod_fscores)
}

math_1pl <- fit_mirt_math(math_mat, "Rasch")
write_rds(math_1pl, here("assessment/colombia/stage2/task_analyses/egma/fits/math_1pl.rds"))

math_2pl <- fit_mirt_math(math_mat, "2PL")
write_rds(math_2pl, here("assessment/colombia/stage2/task_analyses/egma/fits/math_2pl.rds"))
```

```{r}
anova(math_1pl$model, math_2pl$model)
math_best <- math_2pl
```

2PL wins - what about multidimensionality?

```{r}
mod2 <- mirt(data = math_mat, model = 2, verbose=TRUE,
             guess = .25, technical = list(NCYCLES = 2000)) # itemtype='2PL',

mod3 <- mirt(data = math_mat, model = 3, verbose=TRUE,
             guess = .25, technical = list(NCYCLES = 2000))

anova(math_best$model, mod2) # 2d preferred by AIC, but not BIC
anova(mod2, mod3) # 3d preferred by AIC, but not BIC
```

## Plot Coefficients

```{r, fig.width=10}
coefs_2pl <- math_best$coefs |>
  left_join(mp |> select(item, subtask, expected_answer) |> distinct()) 

ggplot(coefs_2pl, 
       aes(x = a1, y = d, col = subtask)) + 
  geom_jitter(alpha = .5, width = .5) + 
  #geom_label(aes(label=item)) + 
  geom_smooth() + 
  facet_wrap(~subtask, scales="free")
```

```{r, fig.height=10, fig.width=5}
coefs_2pl |> ggplot(aes(x = reorder(item, -d), y = d, col = subtask)) + # labels = expected_answer
  geom_point(alpha = .5, width = .5) + xlab("Item") + ylab("difficulty") +
  coord_flip() + facet_wrap(~subtask, scales="free")
ggsave(file="plots/math-item-difficulty.png")
```




```{r}
math_ntr <- math_ntr |>
  left_join(math_best$fscores)
GGally::ggpairs(ungroup(math_ntr) |> select(-user_id, -run_id), mapping=aes(alpha=.3))
# ggsave("plots/age_n_acc_ability.png", width=9, height=9)
```

```{r, fig.width=4, fig.height=4}
math_ntr |> filter(age<=12) |>
  ggplot(aes(x=age, y=ability)) +
  geom_point(alpha=.3) +
  geom_smooth() + ylab("Score") + xlab("Age (years)") 
```
```{r}
mp |> group_by(user_id, run_id, age, subtask) |>
  #filter(subtask!="fraction") |> # reorder subtask by difficulty?
  summarise(prop_correct = mean(is_correct), n = n()) |>
  filter(n>1) |>
  ggplot(aes(x=age, y=prop_correct)) +
    facet_wrap(. ~ subtask) + 
    geom_point(alpha=.3) + 
  geom_smooth()
```



Save parameters

```{r}
math_scores <- math_best$fscores |>
  rename(score = ability) |>
  mutate(task = "egma-math", score_type = "ability (2PL)")

write_rds(math_scores, here("assessment/colombia/stage2/scores/math_scores.rds"))
```

## Number line comparison

See `number_line.qmd`