```{r load-data}
source(here::here("assessment/colombia/stage2/_setup.R"))

trials_coded <- read_rds(here("assessment/colombia/stage2/data_processed/trials_coded.rds"))
participants <- read_rds(here("assessment/colombia/stage2/data_processed/participants.rds"))
```

```{r}
roar <- trials_coded |>
  filter(task_group == "ROAR") |>
  select(task_id, user_id, run_id, trial_id, item, response, is_correct, rt, age,
         theta_estimate, server_timestamp) |>
  mutate(rt = as.numeric(rt))
  # nest(data = -task)
```

```{r}
roar_theta <- roar |>
  filter(!is.na(theta_estimate)) |>
  arrange(task_id, user_id, run_id, server_timestamp) |>
  group_by(task_id, user_id, run_id) |>
  mutate(trial = 1:n()) |>
  ungroup()

# ggplot(roar_theta, aes(x = trial, y = theta_estimate)) +
#   geom_line(aes(group = user_id))

roar_theta_summary <- roar_theta |>
  group_by(task_id, user_id) |>
  filter(server_timestamp == max(server_timestamp)) |>
  select(task_id, user_id, age, theta_estimate, n_trials = trial) |>
  ungroup()

ggplot(roar_theta_summary, aes(x = age, y = theta_estimate)) +
  geom_point() +
  geom_smooth(method = "lm")

roar_summary <- roar |>
  group_by(task_id, user_id, run_id, age) |>
  summarise(prop_correct =  mean(is_correct),
            total_correct = sum(is_correct),
            n = n()) |>
  ungroup()
```

```{r}
ggplot(roar_summary, aes(x = age, y = prop_correct)) +   
  facet_wrap(vars(task_id)) +
  geom_point() + geom_smooth(method = "lm")

ggplot(roar_summary, aes(x = n)) + 
  geom_histogram(bins = 10)
```

Write out parameters

```{r}
roar_sumscores <- roar_summary |>
  mutate(score = case_when(
    task_id == "sre-es" ~ total_correct,
    task_id == "vocab" ~ prop_correct,
    TRUE ~ NA)) |>
  mutate(score_type = case_when(
    task_id == "sre-es" ~ "total correct",
    task_id == "vocab" ~ "proportion correct",
    TRUE ~ NA)) |>
  filter(!is.na(score)) |>
  select(task = task_id, user_id, score, score_type)

# roar_sumscores <- roar_summary |>
#   filter(!(task_id %in% unique(roar_theta_summary$task_id))) |>
#   select(task = task_id, user_id, score = prop_correct) |>
#   mutate(score_type = "proportion correct")

roar_thetas <- roar_theta_summary |>
  select(task = task_id, user_id, score = theta_estimate) |>
  mutate(score_type = "ability")

roar_scores <- bind_rows(roar_sumscores, roar_thetas)

write_rds(roar_scores, here("assessment/colombia/stage2/scores/roar_scores.rds"))
```
