---
format: html
---

```{r}
library(tidyverse)
library(ggthemes)
source(here("plot_settings.R"))

all_coefs <- read_rds("02_scoring_outputs/all_coefs.rds")
```

hf

```{r}
hf_coefs <- all_coefs |>
  filter(task == "hf") |>
  select(model_set, subset, itemtype, invariance, group, item, a1, d) |>
  pivot_longer(c(a1, d), names_to = "param", values_to = "value") |>
  filter(!(param == "a1" & itemtype == "rasch")) |>
  mutate(group = if_else(model_set == "by_language", subset, group) |>
           fct_recode("pilot_mpieva_de" = "de", "pilot_uniandes_co" = "es", "pilot_western_ca" = "en")) |>
  separate(item, into = c("block", "stimulus", "trial_type")) |>
  unite(col = "item", "block", "stimulus") |>
  mutate(item = item |> fct_recode("hf_heart" = "heartsflowers_heart",
                                   "hf_flower" = "heartsflowers_flower",
                                   "heart" = "hearts_heart",
                                   "flower" = "flowers_flower"))

hf_coefs |> #invariance == "metric", 
  filter(model_set == "multigroup_site", itemtype == "rasch") |>
ggplot(aes(y = value, x = item, colour = trial_type)) +
  # facet_wrap(vars(model_set, itemtype, invariance)) +
  # facet_wrap(vars(invariance, group)) +
  facet_grid(vars(invariance), vars(group)) +
  geom_crossbar(aes(ymin = value, ymax = value), position = "dodge", width = 0.5, middle.linewidth = 1) +
  # geom_point(size = 1) +
  scale_color_ptol() +
  scale_y_continuous(limits = ~range(.x, 0)) +
  labs(x = "Item", y = "Difficulty")
ggsave("plots/hf_coefs_nostart.png", width = 10, height = 3)
```

mrot

```{r}
mrot_coefs <- all_coefs |>
  filter(task == "mrot", model_set == "multigroup_site", subset == "overlap_items") |>
  select(model_set, subset, itemtype, invariance, group, item, a1, d) |>
  pivot_longer(c(a1, d), names_to = "param", values_to = "value") |>
  separate(item, into = c("task", "dimension", "shape", "angle")) |>
  unite("stimulus", dimension, shape) |>
  mutate(itemtype = itemtype |> as_factor() |> fct_relevel("rasch"),
         invariance = invariance |> as_factor() |> fct_relevel("configural", "scalar"))
  
mrot_coefs |>
  filter(param == "d") |>
ggplot(aes(x = angle, y = value, colour = stimulus)) +
  facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_point() +
  geom_line(aes(group = stimulus)) +
  scale_colour_ptol() +
  labs(x = "Angle", y = "Difficulty")
ggsave("plots/mrot_difficulty.png", width = 10, height = 8)

mrot_coefs |>
  filter(param == "a1", itemtype != "rasch") |>
ggplot(aes(x = angle, y = value, colour = stimulus)) +
  facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_point() +
  geom_line(aes(group = stimulus)) +
  scale_colour_ptol() +
  labs(x = "Angle", y = "Discrimination")
ggsave("plots/mrot_discrimination.png", width = 10, height = 6)
```

tom

```{r}
tom_items <- task_data_nested |>
  filter(item_task == "tom") |>
  unnest(data) |>
  distinct(item_uid, item_group, item) |>
  mutate(item_type = str_remove(item, "_.$")) |>
  mutate(story = str_extract(item_uid, "(?<=tom_story)[0-9]+") |> as.numeric()) |>
  arrange(story) |>
  mutate(story = paste("story", story) |> fct_inorder())

tom_coefs <- all_coefs |>
  filter(task == "tom") |>
  filter(model_set == "by_language", itemtype == "rasch") |>
  mutate(group = if_else(model_set == "by_language", subset, group) |>
           fct_recode("pilot_mpieva_de" = "de", "pilot_uniandes_co" = "es", "pilot_western_ca" = "en")) |>
  select(model_set, subset, itemtype, invariance, group, item, a1, d) |>
  pivot_longer(c(a1, d), names_to = "param", values_to = "value") |>
  filter(!(param == "a1" & itemtype == "rasch")) |>
  rename(item_uid = item) |>
  left_join(tom_items)

item_groups <- tom_items |> distinct(item_group) |> pull(item_group)
item_types <- unique(tom_coefs$item_type)

tom_coef_plot <- \(grp) {
  tom_coefs |>
    filter(param == "d") |> filter(item_group == grp) |> mutate(item_group = item_group |> str_replace("_", " ")) |>
    ggplot(aes(x = value, y = item, colour = item_type)) +
    facet_grid(vars(item_group, story), vars(group), scales = "free_y", space = "free_y") +
    geom_vline(xintercept = 0, color = "darkgrey", linetype = "dotted") +
    geom_crossbar(aes(xmin = value, xmax = value), orientation = "y", position = "dodge", width = 0.5, middle.linewidth = 1) +
    scale_color_manual(values = ptol_pal()(length(item_types)) |> set_names(item_types)) +
    labs(x = "Difficulty", y = "Item", colour = "Item type",
         caption = "Model: By language Rasch") +
    theme(panel.border = element_rect(),
          strip.text.y = element_text(size = rel(0.9), vjust = 0))
  ggsave(glue("plots/tom_difficulty_{grp}.png"), width = 11, height = 7)
}

walk(item_groups, tom_coef_plot)
```

sds

```{r}
sds_coefs <- all_coefs |>
  filter(task == "sds", model_set == "multigroup_site") |> #, subset == "all_items") |>
  select(model_set, subset, itemtype, invariance, group, item, a1, difficulty) |>
  pivot_longer(c(a1, difficulty), names_to = "param", values_to = "value") |>
  filter(!(param == "a1" & itemtype == "rasch")) |>
  separate(item, into = c("task", "block", "trial_type", "trial_status")) |>
  unite("item", trial_type, trial_status, remove = FALSE, na.rm = TRUE) |>
  mutate(itemtype = itemtype |> as_factor() |> fct_relevel("rasch"),
         invariance = invariance |> as_factor() |> fct_relevel("configural", "scalar"),
         block = block |> fct_recode(dims = "dimensions"))

sds_coefs |>
  # filter(param == "difficulty") |>
  # filter(param == "d", !(block %in% c("dimensions", "same"))) |>
  ggplot(aes(y = value, x = block, colour = trial_type)) +
  facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_hline(yintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(ymin = value, ymax = value), position = "dodge", width = 0.5, middle.linewidth = 0.5) +
  scale_color_manual(values = c(rev(ptol_pal()(4)), rev(ptol_pal()(6)))) +
  # scale_color_ptol() +
  scale_y_continuous(limits = ~range(.x, 0)) +
  labs(x = "Block", y = "Difficulty", colour = "Item") +
  theme(panel.border = element_rect())
ggsave("plots/sds_difficulty.png", width = 11, height = 8)

sds_rasch_scalar <- sds_coefs |>
  filter(param == "difficulty", subset == "all_items",
         invariance == "scalar", itemtype == "rasch",
         str_detect(block, "match")) |>
  select(-group) |>
  distinct() |>
  # arrange(value) |>
  mutate(trial_type = trial_type |> as_factor() |> fct_rev()) |>
  mutate(trial_status = if_else(trial_type == "choice1", "start",
                                str_sub(trial_status, 1, 1)),
         trial_status = trial_status |> fct_relevel("start"))
         # block = block |> fct_inorder())

ggplot(sds_rasch_scalar, aes(x = value, y = trial_type, colour = trial_status)) +
  facet_grid(rows = vars(block), scales = "free", space = "free") +
  # facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_vline(xintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(xmin = value, xmax = value), middle.linewidth = 0.5) +
                # position = "dodge", width = 0.5) +
  # scale_color_manual(values = c(rev(ptol_pal()(4)), rev(ptol_pal()(6)))) +
  # scale_color_ptol() +
  # scale_color_viridis_d() +
  scale_colour_manual(values = c("black", scales::pal_brewer(palette = "Spectral")(4))) +
  # scale_colour_brewer(palette = "Spectral") +
  # scale_y_continuous(limits = ~range(.x, 0)) +
  labs(y = "", x = "Difficulty", colour = "Previous matches") +
  theme(#panel.border = element_rect(),
        panel.grid.major.y = element_line(colour = "#EBEBEBFF"),
        legend.position = "top",
        # legend.title = element_blank(),
        axis.title.y = element_blank())
ggsave("sds_difficulty_status.png", width = 6, height = 5)

g_s <- all_coefs |>
  filter(task == "sds", subset == "all_items", invariance == "scalar",
         itemtype == "rasch", str_detect(item, "match")) |>
  select(item_uid = item, g) |> distinct()

sds_sumscores <- trial_data_coded |>
  filter(item_task == "sds") |>
  group_by(site, item_group, item_uid, chance) |>
  summarise(prop = mean(correct), n = n()) |>
  ungroup() |>
  separate(item_uid, into = c("task", "block", "trial_type", "trial_status"),
           remove = FALSE) |>
  unite("item", trial_type, trial_status, remove = FALSE, na.rm = TRUE) |>
  mutate(block = block |> fct_recode(dims = "dimensions")) |>
  mutate(trial_type = trial_type |> as_factor() |> fct_rev(),
         item = item |> as_factor() |> fct_rev()) |>
  mutate(trial_status = trial_status |> replace_values()) |>
  mutate(trial_status = if_else(trial_type == "choice1", "start",
                                str_sub(trial_status, 1, 1)),
         trial_status = trial_status |> fct_relevel("start")) |>
  left_join(g_s)

sds_sumscores |> filter(str_detect(block, "match")) |>
ggplot(aes(x = prop, y = trial_type, colour = trial_status)) +
  facet_grid(cols = vars(site), rows = vars(block), scales = "free", space = "free") +
  # facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_vline(xintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(xmin = prop, xmax = prop), middle.linewidth = 0.5) +
  scale_x_continuous(transform = "reverse") +
  scale_colour_manual(values = c("black", scales::pal_brewer(palette = "Spectral")(4))) +
  labs(y = "Block", x = "Proportion correct", colour = "Item") +
  theme(#panel.border = element_rect(),
        panel.grid.major.y = element_line(colour = "#EBEBEBFF"),
        legend.position = "top",
        axis.title.y = element_blank())
ggsave("sds_sumscores_status.png", width = 8, height = 5)

sds_sumscores |> filter(str_detect(block, "match")) |>
  arrange(trial_status, as.character(trial_type)) |>
  mutate(item = item |> fct_inorder() |> fct_rev()) |>
ggplot(aes(x = prop, y = item, colour = trial_status)) +
  facet_grid(cols = vars(site), rows = vars(block), scales = "free", space = "free") +
  # facet_grid(vars(itemtype, invariance), vars(group)) +
  # geom_vline(xintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(xmin = g, xmax = g), middle.linewidth = 0.5,
                linewidth = 0.3, colour = "lightgrey", width = 0.7) +
  geom_crossbar(aes(xmin = prop, xmax = prop), middle.linewidth = 0.5) +
  # scale_x_continuous(transform = "reverse") +
  scale_colour_manual(values = c("black", scales::pal_brewer(palette = "Spectral")(4))) +
  labs(y = "Block", x = "Proportion correct", colour = "Item") +
  theme(#panel.border = element_rect(),
        panel.grid.major.y = element_line(colour = "#EBEBEBFF"),
        legend.position = "top",
        axis.title.y = element_blank())
ggsave("sds_sumscores_status_expanded.png", width = 8, height = 8)


sds_coefs |>
  filter(param == "d", block == "dims") |>
  # filter(param == "d", !(block %in% c("dimensions", "same"))) |>
  ggplot(aes(y = value, x = block, colour = trial_type)) +
  facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_hline(yintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(ymin = value, ymax = value), position = "dodge", width = 0.5, middle.linewidth = 0.5) +
  scale_color_manual(values = rev(ptol_pal()(5))) +
  # scale_color_ptol() +
  scale_y_continuous(limits = ~range(.x, 0)) +
  labs(x = "Block", y = "Difficulty", colour = "Item") +
  theme(panel.border = element_rect())
ggsave("plots/sds_dims.png", width = 7, height = 8)

sds_coefs |>
  filter(param == "a1", !(block %in% c("dimensions", "same"))) |>
  ggplot(aes(y = value, x = block, colour = trial_type)) +
  facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_hline(yintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(ymin = value, ymax = value), position = "dodge", width = 0.5, middle.linewidth = 1) +
  scale_color_manual(values = rev(ptol_pal()(9))) +
  scale_y_continuous(limits = ~range(.x, 0)) +
  labs(x = "Block", y = "Discrimination", colour = "Item") +
  theme(panel.border = element_rect())
ggsave("plots/sds_discrimination.png", width = 8, height = 6)

sds_coefs |>
  filter(itemtype == "2pl", !(block %in% c("dimensions", "same"))) |>
  pivot_wider(names_from = param, values_from = value) |>
  # unite("item", c("block", "trial_type")) |>
  ggplot(aes(x = d, y = a1, colour = trial_type, shape = block)) +
  facet_grid(vars(itemtype, invariance), vars(group)) +
  geom_point(size = 1) +
  # geom_hline(yintercept = 0, color = "darkgrey", linetype = "dotted") +
  # geom_crossbar(aes(ymin = value, ymax = value), position = "dodge", width = 0.5, middle.linewidth = 1) +
  scale_color_manual(values = rev(ptol_pal()(9))) +
  # scale_y_continuous(limits = ~range(.x, 0)) +
  labs(x = "Difficulty", y = "Discrimination", colour = "Item", shape = "Block") +
  theme(panel.border = element_rect())
ggsave("sds_diff_disc.png", width = 9.5, height = 6)
```

```{r}
task_data_nested <- read_rds(here("01_fetched_data/task_data_nested.rds"))
sds_data <- task_data_nested |> filter(item_task == "sds") |> unnest(data)

sds_props <- sds_data |>
  group_by(site, item_uid, item_group, item) |>
  summarise(prop_correct = mean(correct), n = n()) |>
  ungroup() |>
  mutate(param = "prop_correct") |>
  rename(group = site, block = item_group, trial_type = item, value = prop_correct)

sds_props |>
  # filter(!(block %in% c("dimensions", "same"))) |>
  ggplot(aes(y = value, x = block, colour = trial_type)) +
  facet_grid(vars(), vars(group)) +
  geom_hline(yintercept = 0, color = "darkgrey", linetype = "dotted") +
  geom_crossbar(aes(ymin = value, ymax = value), position = "dodge", width = 0.5, middle.linewidth = 1) +
  # scale_color_manual(values = rev(ptol_pal()(4))) +
  scale_color_manual(values = c(rev(ptol_pal()(4)), rev(ptol_pal()(6)))) +
  scale_y_continuous(limits = ~range(.x, 0)) +
  labs(x = "Block", y = "Proportion correct", colour = "Item") +
  theme(panel.border = element_rect())
ggsave("sds_props.png", width = 9, height = 4)
```
