```{r setup}
library(tidyverse)
library(here)
library(glue)

source(here("03_summaries", "plotting_helper.R"))
runs <- read_rds(here("01_fetched_data/run_data.rds"))
```

# Task durations

```{r}
task_data <- read_rds(here(glue("01_fetched_data/task_data_nested.rds"))) |>
  unnest(data)
```


Table of median task times

Vocabulary - CAT (DE & CO)
Sentence Understanding - CAT (DE & CO)
Same & Different (CAT if available for DE & CO)
Shape Rotation - CAT (DE & CO)
Pattern Matching (DE new corpus; CO CAT)
Math (DE new corpus; CO old corpus)
Hearts & Flowers (DE & CO)
Memory (DE & CO)
Stories (DE - 2 waves, 2 new corpora; CO - 1 new corpus?)


```{r}
times <- task_data |>
  mutate(timestamp = as_datetime(timestamp)) |>
  group_by(run_id, site) |>
  summarise(time = mean(timestamp))

ggplot(times, aes(x = time, fill = site)) +
  geom_histogram() 

ggsave(here("03_summaries", "plots", "data_waves.png"),
        width = 6, height = 3, create.dir = TRUE)
```


```{r}
time_summary <- task_data |>
  arrange(run_id, timestamp) |>
  group_by(site, item_task, run_id) |>
  summarise(trials = n(),
            start = min(timestamp), end = max(timestamp)) |>
  ungroup() |>
  mutate(diff = difftime(end, start, units = "mins")) |>
  left_join(runs |> select(run_id, is_cat = adaptive, completed)) |>
  filter(trials > 2, completed)

# ggplot(time_summary, aes(x = diff)) +
#   facet_wrap(vars(site, task_id)) +
#   geom_histogram()

task_time_summary <- time_summary |>
  group_by(site, item_task, is_cat) |>
  summarise(median_diff = median(diff),
            min_diff = min(diff),
            max_diff = max(diff)) |>
  ungroup() |>
  mutate(across(contains("diff"), \(d) round(d, 2))) |>
  mutate(combined_diff = glue("{median_diff} [{min_diff}, {max_diff}]"))

write_csv(task_time_summary, here("03_summaries","tables","task_time_summary.csv"))
```


```{r}
task_time_wide_nocat <- task_time_summary |>
  filter(!is_cat) |>
  select(item_task, site, median_diff) |>
  pivot_wider(names_from = site, values_from = median_diff)

write_csv(task_time_wide, here("03_summaries","tables","task_time_wide.csv"))

task_time_wide_cat <- task_time_summary |>
  filter(is_cat) |>
  select(item_task, site, median_diff) |>
  pivot_wider(names_from = site, values_from = median_diff)

write_csv(task_time_wide_cat, here("03_summaries","tables","task_time_wide_cat.csv"))
```

# Survey durations

```{r}
survey_data <- read_rds(here(glue("01_fetched_data/survey_data_nested.rds"))) |>
  unnest(data) 

time_surveys <- survey_data |>
  mutate(timestamp = as_datetime(timestamp)) |>
  arrange(user_id, timestamp) |>
  group_by(site, survey_type, dataset, user_id) |>
  summarise(trials = n(),
            start = min(timestamp), end = max(timestamp)) |>
  ungroup() |>
  mutate(diff = difftime(end, start, units = "mins")) |>
  filter(diff < 200)

survey_time_summary <- time_surveys |>
  group_by(site, survey_type, dataset) |>
  summarise(median_diff = median(diff),
            min_diff = min(diff),
            max_diff = max(diff))

```

```{r}
ggplot(time_surveys, aes(x = diff))
```
