```{r setup}
library(tidyverse)
library(here)
library(glue)
library(lavaan)
library(tidySEM)
library(ggthemes)

source(here("03_summaries/plotting_helper.R"))
source(here("03_summaries/scores_helper.R"))
```

```{r}
sites <- c("ca_pilot", "co_pilot", "de_pilot")

task_scores <- read_rds(here("02_scoring_outputs","scores",
                             "multigroup_scores.rds"))  |>
  bind_rows(read_rds(here("02_scoring_outputs","scores",
                          "scores_general.rds")))  |>
  bind_rows(read_rds(here("02_scoring_outputs","scores",
                          "roar_thetas.rds"))) |>
  filter(site %in% sites)
```

```{r}
run_ages <- read_rds(here(glue("01_fetched_data/run_data.rds"))) |>
  select(site, task_id, user_id, run_id, age) |>
  filter(site %in% sites)
```


# Factor analysis


```{r}
ages <- run_ages |>
  group_by(user_id) |>
  summarise(age = mean(age, na.rm=TRUE))


scores_wide <- task_scores |>
  select(item_task, metric_value, user_id, site) |>
  pivot_wider(names_from = "item_task", values_from = "metric_value", 
              id_cols = c("user_id","site"), 
              values_fn = mean) 

scores_wide_mat <- scores_wide |>
  janitor:::clean_names() |>
  mutate(across(ha:swr, ~ scale(.x)[,1])) |>
  left_join(ages)
```

# EFA




# CFA 

```{r}
cfa_model <-  "
reasoning =~ matrix + mrot 
ef =~ hf + mg + sds + mefs
social =~ ha + tom
language =~ trog + vocab + sre + swr + pa
maths =~ math
"

fit <- cfa(cfa_model, scores_wide_mat, std.lv=TRUE, missing='fiml')
summary(fit, fit.measures=TRUE, standardize=TRUE)
```

```{r}
layout = matrix(nrow=4, ncol = 14, 
                data = c("matrix", "mrot", "hf","mg", "sds", "mefs", "tom","ha", "trog","vocab","sre","swr","pa","math",
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
                         "reasoning",NA, "ef", NA, NA, NA, "social", NA,  "language",NA, NA, NA, NA,
                         "maths"
                ), byrow = TRUE)

graph_sem(model = fit, text_size = 3, layout = t(layout)) + 
  theme(panel.background = element_rect(fill = "white"))
ggsave(here("03_summaries/plots/sem_all.png"), width = 14, height = 10)

```

Add age. 

```{r}
cfa_model_age <-  "
# measurement
reasoning =~ matrix + mrot 
ef =~ hf + mg + sds + mefs
social =~ ha + tom
language =~ trog + vocab + sre + swr + pa
maths =~ math

# age regressions
reasoning ~ age
ef ~ age
social ~ age
language ~ age
maths ~ age
"

fit_age <- cfa(cfa_model_age, scores_wide_mat, std.lv=TRUE, missing='fiml')
summary(fit_age, fit.measures=TRUE, standardize=TRUE)


layout_age = matrix(nrow=7, ncol = 14, 
                data = c("matrix", "mrot", "hf","mg", "sds", "mefs", "tom","ha", "trog","vocab","sre","swr","pa","math",
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         "reasoning",NA, "ef", NA, NA, NA,  "social", NA, "language",NA, NA, NA, NA, "maths",
                         NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, NA,NA, 
                         NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, NA,NA, 
                         NA, NA, NA, NA, NA, NA, "age", NA, NA,  NA, NA, NA, NA,NA
                         
                ), byrow = TRUE)


graph_sem(model = fit_age, text_size = 3, layout = t(layout_age)) + 
  theme(panel.background = element_rect(fill = "white"))
ggsave(here("03_summaries/plots/sem_age.png"), width = 14, height = 10)
```

Add site grouping - this is an invariant mdoel tha

```{r}
fit_age_site <- cfa(cfa_model_age, scores_wide_mat, 
                    group = "site", 
                    std.lv=TRUE, missing='fiml')
summary(fit_age_site, fit.measures=TRUE, standardize=TRUE)


layout_age = matrix(nrow=7, ncol = 12, 
                    data = c(
                      "matrix_reasoning", "mental_rotation", "hearts_and_flowers","memory_game", "same_different_selection", "theory_of_mind","trog","vocab","sre","swr","pa","egma_math",
                      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                      "reasoning",NA, "ef", NA, NA, "social","language",NA, NA, NA, NA,
                      "math",
                      NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, 
                      NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, 
                      NA, NA, NA, NA, NA, NA, "age", NA, NA,  NA, NA, NA
                    ), byrow = TRUE)

graph_sem(model = fit_age, text_size = 3, layout = t(layout_age)) + 
  theme(panel.background = element_rect(fill = "white"))
ggsave(here("03_summaries/plots/sem_age.png"), width = 14, height = 10)
```

# Alternative models

# Granular construct structure

```{r}
cfa_model <-  "
reasoning =~ matrix_reasoning
spatial =~ mental_rotation 
ef =~ hearts_and_flowers + memory_game + same_different_selection
social =~ theory_of_mind
language =~ trog + vocab 
reading =~ sre + swr + pa
math =~ egma_math
"

fit <- cfa(cfa_model, scores_wide_mat, std.lv=TRUE, missing='fiml')
summary(fit, fit.measures=TRUE, standardize=TRUE)
```

```{r}
layout = matrix(nrow=4, ncol = 12, 
                data = c("matrix_reasoning", "mental_rotation", "hearts_and_flowers","memory_game", "same_different_selection", "theory_of_mind","trog","vocab","sre","swr","pa","egma_math",
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         "reasoning","spatial", "ef", NA, NA, "social", "language",NA, "reading", NA, NA,
                         "math"
                ), byrow = TRUE)

graph_sem(model = fit, text_size = 3, layout = t(layout)) + 
  theme(panel.background = element_rect(fill = "white"))
ggsave(here("03_summaries/plots/sem_all_granular.png"), width = 14, height = 10)

```

Add age. 

```{r}
cfa_model_age <-  "
# measurement
reasoning =~ matrix_reasoning
spatial =~ mental_rotation 
ef =~ hearts_and_flowers + memory_game + same_different_selection
social =~ theory_of_mind
language =~ trog + vocab 
reading =~ sre + swr + pa
math =~ egma_math

# age regressions
reasoning ~ age
spatial ~ age
ef ~ age
social ~ age
language ~ age
reading ~ age
math ~ age
"

fit_age <- cfa(cfa_model_age, scores_wide_mat, std.lv=TRUE, missing='fiml')
summary(fit_age, fit.measures=TRUE, standardize=TRUE)


layout_age = matrix(nrow=7, ncol = 12, 
                    data = c(
                      "matrix_reasoning", "mental_rotation", "hearts_and_flowers","memory_game", "same_different_selection", "theory_of_mind","trog","vocab","sre","swr","pa","egma_math",
                      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                      "reasoning","spatial", "ef", NA, NA, "social","language",NA, "reading", NA, NA,
                      "math",
                      NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, 
                      NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, 
                      NA, NA, NA, NA, NA, NA, "age", NA, NA,  NA, NA, NA
                    ), byrow = TRUE)

graph_sem(model = fit_age, text_size = 3, layout = t(layout_age)) + 
  theme(panel.background = element_rect(fill = "white"))
ggsave(here("03_summaries/plots/sem_age_granular.png"), width = 14, height = 10)
```


# Site specific

```{r}

cfa_model_age_de <-  "
# measurement
reasoning =~ matrix_reasoning + mental_rotation 
ef =~ hearts_and_flowers + memory_game + same_different_selection
social =~ theory_of_mind 
language =~ trog + vocab 
math =~ egma_math

# age regressions
reasoning ~ age
ef ~ age
social ~ age
language ~ age
math ~ age
"

layout_age_de = matrix(nrow=7, ncol = 12, 
                       data = c(
                         "matrix_reasoning", "mental_rotation", "hearts_and_flowers","memory_game", "same_different_selection", "theory_of_mind","trog","vocab","sre-de","swr-de",NA,"egma_math",
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
                         "reasoning",NA, "ef", NA, NA, "social","language",NA, NA, NA, NA,
                         "math",
                         NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, 
                         NA, NA, NA, NA, NA, NA, NA, NA,  NA, NA, NA, NA, 
                         NA, NA, NA, NA, NA, NA, "age", NA, NA,  NA, NA, NA
                       ), byrow = TRUE)

fit_age_de <- cfa(cfa_model_age_de, 
                  filter(scores_wide_mat, site == "de_pilot"),
                  std.lv=TRUE, missing='fiml')
# summary(fit_age, fit.measures=TRUE, standardize=TRUE)


graph_sem(model = fit_age_de, text_size = 3, layout = t(layout_age_de)) + 
  theme(panel.background = element_rect(fill = "white"))
# ggsave(here("03_summaries/plots/extra/sem_age_de.png"), width = 14, height = 10)
```


```{r}

cfa_model_age_co <-  "
# measurement
reasoning =~ matrix_reasoning + mental_rotation 
ef =~ hearts_and_flowers + memory_game + same_different_selection
social =~ theory_of_mind 
language =~ trog + vocab 
math =~ egma_math

# age regressions
reasoning ~ age
ef ~ age
social ~ age
language ~ age
math ~ age
"

fit_age_co <- cfa(cfa_model_age_co, 
                  filter(scores_wide_mat, site == "co_pilot"),
                  std.lv=TRUE, missing='fiml')
# summary(fit_age, fit.measures=TRUE, standardize=TRUE)


graph_sem(model = fit_age_co, text_size = 3, layout = t(layout_age_de)) + 
  theme(panel.background = element_rect(fill = "white"))
# ggsave(here("03_summaries/plots/extra/sem_age_de.png"), width = 14, height = 10)
```

# Age exploration

Let's try a model that adds log age instead of / as well as age. 

```{r}
scores_wide_mat$log_age <- log(scores_wide_mat$age)
cfa_age_model <-  "
# measurement
reasoning =~ matrix_reasoning + mental_rotation 
ef =~ hearts_and_flowers + memory_game  + same_different_selection
social =~ theory_of_mind 
language =~ trog + vocab + sre + swr
math =~ egma_math

# age regressions
reasoning ~ age + log_age
ef ~ age + log_age
social ~ age + log_age
language ~ age + log_age
math ~ age + log_age
"

fit <- sem(cfa_age_model, scores_wide_mat, std.lv=TRUE, missing='fiml')
summary(fit, fit.measures=TRUE, standardize=TRUE)

layout = matrix(nrow=4, ncol = 14, 
                data = c(NA,NA,NA,NA, NA,NA,"log_age", "age", NA,NA,NA,NA, NA, NA,
                         NA,NA,NA,NA, NA,NA,NA,NA, NA,NA,NA,NA, NA, NA,
                         "reasoning",NA, "ef", NA, NA, NA, "social",NA, NA, "language",NA, NA, NA, 
                         "math",
                         "matrix_reasoning", "mental_rotation", "hearts_and_flowers","memory_game","mefs", "same_different_selection",  "theory_of_mind","hostile_attribution","emotion_reasoning","trog","vocab","sre_es","swr_es","egma_math"), byrow = TRUE)

graph_sem(model = fit, text_size = 3, layout = t(layout))
```

Median split on age

```{r}
fit_younger <- cfa(cfa_model, data = filter(scores_wide_mat, age < 9),
                   std.lv=TRUE, missing='fiml')
fit_older <- cfa(cfa_model, data = filter(scores_wide_mat, age >= 9),
                 std.lv=TRUE, missing='fiml')
summary(fit_younger, fit.measures=TRUE, standardize=TRUE)
summary(fit_older, fit.measures=TRUE, standardize=TRUE)

graph_sem(model = fit_younger, text_size = 3, layout = layout)
graph_sem(model = fit_older, text_size = 3, layout = layout)
```
