```{r load-data}
source(here::here("assessment/colombia/stage2/_setup.R"))

trials_coded <- read_rds(here("assessment/colombia/stage2/data_processed/trials_coded.rds"))
participants <- read_rds(here("assessment/colombia/stage2/data_processed/participants.rds"))
```

```{r}
mxr <- trials_coded |>
  filter(task_id == "matrix-reasoning") |>
  select(user_id, run_id, item, response, is_correct, rt, age, server_timestamp) |>
  mutate(rt = as.numeric(rt))
```

```{r}
mxr_summary <- mxr |> 
  group_by(user_id, age) |>
  summarise(prop_correct =  mean(is_correct), 
            n = n()) |>
  ungroup()
```

```{r}
ggplot(mxr_summary, aes(x = n)) + 
  geom_histogram(bins = 10)
```

Classic confounding of sum score and n trials.

```{r}
ggplot(mxr_summary, aes(x = n, y = prop_correct)) +   
  geom_point() + geom_smooth(method = "lm")
```

## IRT Models

```{r}
mxr_first_runs <- mxr |>
  group_by(user_id) |>
  filter(server_timestamp == min(server_timestamp)) |>
  select(user_id, run_id)

matr |> count(user_id, item) |> filter(n > 1)

mxr_wide <- mxr |>
  inner_join(mxr_first_runs) |>
  mutate(is_correct = as.numeric(is_correct)) |>
  group_by(user_id, item) |>
  slice(1) |> # duplicates??
  select(user_id, item, is_correct) |>
  pivot_wider(names_from = "item", values_from = "is_correct") |>
  ungroup()

mxr_mat <- as.matrix(select(mxr_wide, -user_id))
rownames(mxr_mat) <- mxr_wide$user_id

# remove columns with no variance
mxr_cols <- colMeans(mxr_mat, na.rm=TRUE) 

mxr_mat <- mxr_mat[,mxr_cols > 0 & mxr_cols < 1]
```

### Fit models

```{r fit-rasch-model}
set.seed(1234)

fit_mirt_mxr <- function(data_mat, item_type) {
  mod <- mirt(data_mat, itemtype = item_type, verbose = TRUE, guess = .25,
              technical = list(NCYCLES = 1000))
  
  mod_coefs <- coef(mod, simplify = TRUE)$items |> as_tibble(rownames = "item")
  
  scores <- fscores(mod, method = "MAP", verbose = FALSE)
  mod_fscores <- tibble(user_id = rownames(data_mat), ability = scores[,1])
  
  list(model = mod, coefs = mod_coefs, fscores = mod_fscores)
}

mxr_1pl <- fit_mirt_mxr(mxr_mat, "Rasch")
write_rds(mxr_1pl, here("assessment/colombia/stage2/task_analyses/matrix_reasoning/fits/mxr_1pl.rds"))

mxr_2pl <- fit_mirt_mxr(mxr_mat, "2PL")
write_rds(mxr_2pl, here("assessment/colombia/stage2/task_analyses/matrix_reasoning/fits/mxr_2pl.rds"))
```

2PL model wins.

```{r}
anova(mxr_1pl$model, mxr_2pl$model)
mxr_best <- mxr_2pl
```

### Coefficients

```{r}
ggplot(mxr_best$coefs, 
       aes(x = reorder(item, -d), y = d)) + 
  geom_jitter(alpha = .5, width = .5) + 
  geom_smooth(method = "lm") + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) + 
  coord_flip()
```

```{r}
mxr_summary <- mxr_summary |> left_join(mxr_best$fscores)
GGally::ggpairs(mxr_summary |> select(-user_id))
```

```{r}
ggplot(mxr_summary, aes(x = prop_correct, y = ability)) + 
  geom_point(aes(size = n), alpha = .5) + 
  geom_smooth(method = "lm")
```

Write out parameters

```{r}
mxr_scores <- mxr_best$fscores |>
  rename(score = ability) |>
  mutate(task = "matrix-reasoning", score_type = "IRT (2PL)")

write_rds(mxr_scores, here("assessment/colombia/stage2/scores/mxr_scores.rds"))
```
