---
format: html
---

```{r setup}
library(mirt)

source(here::here("assessment","colombia","stage2","_setup.R"))

trials_coded <- read_rds(here("assessment", "colombia", "stage2", "data_processed", "trials_coded.rds"))
participants <- read_rds(here("assessment", "colombia", "stage2", "data_processed", "participants.rds"))
```

```{r}
# ntl_threshold <- .05
score_ntl <- function(item, answer, response, threshold = 0.05) {
  max_value <- as.numeric(str_extract(item, "\\d+(?=\\})"))
  abs(as.numeric(response) - as.numeric(answer)) / max_value < threshold
}

trials_numberline <- trials_coded |>
  filter(!is.na(item), str_detect(task, "line 4afc|line slider")) |>
  select(subtask, item, expected_answer, user_id, run_id, response) |> # assessment_pid had some NAs
  mutate(subtask = fct_recode(subtask, "ntl" = "number line slider", "ltn" = "number line 4afc")) |>
  pivot_wider(names_from = subtask, values_from = response) |>
  mutate(correct_ltn = expected_answer == ltn,
         correct_ntl_5 = score_ntl(item, expected_answer, ntl, 0.05),
         correct_ntl_10 = score_ntl(item, expected_answer, ntl, 0.1),
         correct_ntl_15 = score_ntl(item, expected_answer, ntl, 0.15)) |>
  select(-ltn, -ntl) |>
  pivot_longer(cols = contains("correct"), names_to = "metric", values_to = "correct")

line_summary <- trials_numberline |>
  mutate(metric = metric |>
           fct_recode("line-to-number" = "correct_ltn",
                      "number-to-line (5%)" = "correct_ntl_5",
                      "number-to-line (10%)" = "correct_ntl_10",
                      "number-to-line (15%)" = "correct_ntl_15") |>
           fct_inorder()) |>
  group_by(item, expected_answer, metric) |>
  summarise(subjects = n_distinct(run_id), # assessment_pid
            trials = n(),
            num_correct = sum(correct, na.rm = TRUE),
            prop_correct = num_correct / trials) |>
  ungroup() |>
  arrange(metric, prop_correct) |>
  mutate(item_label = paste(str_replace(item, "'0': (\\d+), '1': (\\d+)", "\\1-\\2"), expected_answer),
         item_label = fct_inorder(item_label),
         item_index = factor(row_number()))
         # item_index = paste(metric, item_label) |> fct_inorder())

ggplot(line_summary, aes(x = prop_correct, y = item_index)) +
  facet_wrap(vars(metric), scales = "free_y", nrow = 1) +
  # geom_hline(aes(yintercept = item_label), color = "lightgrey") +
  geom_point() +
  # scale_x_continuous(breaks = round(unique(ltn$prop_correct), 2)) +
  scale_y_discrete(breaks = line_summary$item_index, labels = line_summary$item_label) +
  labs(x = "Proportion correct responses", y = "Item") +
  theme(panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.2))
ggsave("plots/line_items.png", width = 12, height = 5)

line_summary |>
  select(item_label, metric, prop_correct) |>
  pivot_wider(names_from = metric, values_from = prop_correct) |>
  pivot_longer(contains("number-"), names_to = "metric", values_to = "correct") |>
  mutate(metric = paste("Percent correct in", metric) |> fct_inorder()) |>
  ggplot(aes(x = `line-to-number`, y = correct)) +
    facet_wrap(vars(metric), switch = TRUE) +
    geom_point() +
    geom_smooth(method = "lm") +
    labs(x = "Percent correct in line-to-number") +
    theme(strip.placement = "outside",
          axis.title.y = element_blank())
ggsave("plots/line_items_corrs.png", width = 10, height = 4)

# ggsave("plots/line_items_ltn.png", width = 9, height = 5)
# ggsave("plots/line_items_ntl.png", width = 8, height = 5)

# ggplot(line_summary, aes(x = prop_correct, y = item_label, color = subtask)) +
#   # facet_wrap(vars(subtask), scales = "free_y") +
#   # geom_hline(aes(yintercept = item_label), color = "lightgrey") +
#   geom_point() +
#   scale_color_ptol() +
#   # scale_x_continuous(breaks = round(unique(ltn$prop_correct), 2)) +
#   labs(x = "Proportion correct responses", y = "Item") +
#   theme(panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.2))
# 
# ggplot(line_summary, aes(x = subtask, y = prop_correct)) +
#   # facet_wrap(vars(subtask), scales = "free_y") +
#   # geom_hline(aes(yintercept = item_label), color = "lightgrey") +
#   geom_point() +
#   geom_line(aes(group = item_label)) +
#   # scale_color_ptol() +
#   # scale_x_continuous(breaks = round(unique(ltn$prop_correct), 2)) +
#   labs(x = "Proportion correct responses", y = "Item") +
#   theme(panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.2))

cor.test(line_summary |> filter(metric=="line-to-number") |> pull(prop_correct),
         line_summary |> filter(metric=="number-to-line (5%)") |> pull(prop_correct)) # .95
cor.test(line_summary |> filter(metric=="line-to-number") |> pull(prop_correct),
         line_summary |> filter(metric=="number-to-line (10%)") |> pull(prop_correct)) # .89
cor.test(line_summary |> filter(metric=="line-to-number") |> pull(prop_correct),
         line_summary |> filter(metric=="number-to-line (15%)") |> pull(prop_correct)) # .83
```

