---
format: html
---

```{r, load-mefs-data}
library(tidyverse)

mefs1 <- read_csv("data/LEVANTE_20240608_1210.csv") %>% # long format data
  filter(`Child ID` != "1234") # remove test
mefs2 <- read_csv("data/LEVANTE_20240608_1225.csv") %>% # N=122; wide format data
  filter(`Child ID` != "1234")

# standardized by age, looks like
cor.test(mefs2$`A1_Standard Score`, mefs2$`A1_Age (Months)`) 
cor.test(mefs2$`A1_Percentile (National)`, mefs2$`A1_Age (Months)`) 

cor.test(mefs2$`A1_Total Score`, mefs2$`A1_Age (Months)`) # r=.56
```

```{r}
mefs_ef <- mefs2 |>
  rename_with(\(nm) nm |> str_to_lower() |> str_replace_all(" ", "_") |> str_remove_all("[\\(\\)]")) |>
  select(child_id, mefs_age = a1_age_months, mefs_score = a1_total_score) |>
  inner_join(ef, by = join_by("child_id" == "user_id"))

mefs_ef |>
  select(child_id, mefs_age, age) |>
  mutate(mefs_age_years = mefs_age / 12,
         age_check = abs(mefs_age_years - age)) |> arrange(desc(age_check))

mefs_ef |>
  select(age, mefs_score, hf_prop_correct, sds_trials, sds_prop_correct,
         mg_prop_correct, mg_span) |>
  GGally::ggpairs()
```
