```{r setup}
library(rlevante)
library(dplyr)
library(here)
library(readr)
library(stringr)
library(tidyr)
```

```{r}
dataset_spec <- list(list(name = "us_downward_extension_pilot:a6kb", version = "4.6"),
                     list(name = "co_bogota_pilot:3j4z",             version = "6.3"),
                     list(name = "co_rural_pilot:66d2",              version = "4.2"),
                     list(name = "de_leipzig_pilot:6c0n",            version = "5.28"),
                     list(name = "ca_western_pilot:97mt",            version = "5.24"))

runs <- get_runs(dataset_spec,
                 remove_incomplete_runs = FALSE,
                 remove_invalid_runs = FALSE)

run_data <- runs |>
  mutate(site = dataset |> str_extract("^.*?(?=:)") |> str_remove("_pilot"),
         .before = everything())

write_rds(run_data, here("01_fetched_data/run_data.rds"), compress = "gz")

survey_data <- get_surveys(dataset_spec)
survey_data_nested <- survey_data |>
  mutate(site = dataset |> str_extract("^.*?(?=:)") |> str_remove("_pilot"),
         .before = everything()) |>
  nest(data = -survey_type)
write_rds(survey_data_nested, here("01_fetched_data/survey_data_nested.rds"),
          compress = "gz")
```

```{r}
trials <- get_trials(dataset_spec,
                     remove_incomplete_runs = FALSE,
                     remove_invalid_runs = FALSE,
                     remove_invalid_trials = FALSE)

trial_data <- trials |>
  separate_wider_delim(dataset, names = c("dataset", "ref", "version"),
                       delim = ":") |>
  mutate(site = dataset |> str_replace("_.*_", "_"),
         .before = everything())
  # nest(data = -c(task_id, item_task, site))
# write_rds(task_data_nested, here("01_fetched_data/task_data_nested.rds"),
          # compress = "gz")

write_rds(trial_data, here("01_fetched_data/trial_data.rds"),
          compress = "gz")
```

```{r}
# trials_raw <- get_trials_raw(dataset_spec)
# 
# trials_uncoded <- trials_raw |>
#   filter(trial_id != "schema_row") |>
#   rlevante:::remove_practice_trials() |>
#   select(dataset, run_id, trial_id, task_id, assessment_stage, corpus_trial_type,
#          trial_index, item_id, item, answer, distractors, server_timestamp) |>
#   anti_join(trial_data, by = "trial_id") |>
#   filter(!is.na(item_id) | item != "" | answer != "") |>
#   arrange(task_id, server_timestamp) |>
#   select(-server_timestamp)
# 
# trials_uncoded |> count(task_id)
# trials_uncoded |> distinct(run_id, task_id) |> count(task_id)
# 
# trials_uncoded_collapsed <- trials_uncoded |>
#   select(-trial_index) |>
#   nest(trial_list = trial_id) |>
#   mutate(trial_list = map_chr(trial_list, \(tt) paste(tt$trial_id, collapse = ",")))
# trials_uncoded_collapsed |> count(task_id, sort = TRUE)
# 
# trials_uncoded_collapsed |> filter(task_id == "egma-math") |> write_csv("items_egma.csv", na = "")
# trials_uncoded_collapsed |> filter(task_id == "hearts-and-flowers") |> write_csv("items_hf.csv", na = "")
# trials_uncoded_collapsed |> filter(task_id == "matrix-reasoning") |> write_csv("items_mxr.csv", na = "")
# trials_uncoded_collapsed |> filter(task_id == "vocab") |> write_csv("items_vocab.csv", na = "")
# trials_uncoded_collapsed |> filter(task_id == "trog") |> write_csv("items_trog.csv", na = "")
# trials_uncoded_collapsed |> filter(task_id == "mental-rotation") |> write_csv("items_mr.csv", na = "")
# 
# trials_uncoded_collapsed |> filter(!(task_id %in% c("memory-game", "same-different-selection"))) |>
#   write_csv("items_multitask.csv", na = "")
# 
# trials_uncoded_collapsed_indexed <- trials_uncoded |>
#   mutate(answer = if_else(task_id == "memory-game", as.character(str_count(answer, ":")), answer)) |>
#   nest(trial_list = trial_id) |>
#   mutate(trial_list = map_chr(trial_list, \(tt) paste(tt$trial_id, collapse = ",")))
# trials_uncoded_collapsed_indexed |> count(task_id, sort = TRUE)
# 
# trials_uncoded_collapsed_indexed |> filter(task_id == "memory-game") |> write_csv("items_mg.csv", na = "")
# trials_uncoded_collapsed_indexed |> filter(task_id == "theory-of-mind") |> write_csv("items_tom_2.csv", na = "")
# trials_uncoded_collapsed_indexed |> filter(task_id == "same-different-selection") |> write_csv("items_sds.csv", na = "")
```
