```{r load-data}
library(tidyverse)
library(glue)
library(here)
library(redivis)
library(rlevante)

source(here("plot_settings.R"))

run_data <- read_rds(here(glue("01_fetched_data/run_data.rds")))
trial_data <- read_rds(here(glue("01_fetched_data/trial_data.rds")))
trials_prelim <- read_rds(here(glue("01_fetched_data/trials_prelim.rds")))
```

```{r}
runs_nonempty <- run_data |> semi_join(trials_prelim, by = "run_id")
write_rds(runs_nonempty, here("01_fetched_data/runs_nonempty.rds"),
          compress = "gz")

runs_filtered <- runs_nonempty |>
  mutate(validation_msg_run = validation_msg_run |> replace_na(""),
         straightlining = str_detect(validation_msg_run, "straightlining")) |>
  # filter to runs completed and no straightlining
  filter(completed & !straightlining) |>
  # filter out task version with known bug
  filter(!(task_version == "1.0.0-beta.19" &
             task_id %in% c("matrix-reasoning", "mental-rotation", "theory-of-mind"))) |>
  # take each user's first run of each task in each administration
  group_by(user_id, task_id, variant_id, administration_id) |>
  arrange(time_started) |>
  slice(1) |>
  ungroup()
write_rds(runs_filtered, here("01_fetched_data/runs_filtered.rds"),
          compress = "gz")

# subset trials to above runs
trial_data_subset <- trial_data |>
  inner_join(runs_filtered |> select(run_id, task_version, language))
write_rds(trial_data_subset, here("01_fetched_data/trial_data_subset.rds"),
          compress = "gz")

# filter out too slow/fast RTs
trial_data_filtered <- trial_data_subset |>
  mutate(validation_msg_trial = validation_msg_trial |> replace_na(""),
         slow_rt = rt_numeric > 30000,
         fast_rt = str_detect(validation_msg_trial, "fast")) |>
  filter(task_id == "same-different-selection" | is.na(rt_numeric) | !slow_rt,
         !fast_rt) |>
  select(-slow_rt, -fast_rt, -valid_trial, -validation_msg_trial)
write_rds(trial_data_filtered, here("01_fetched_data/trial_data_filtered.rds"),
          compress = "gz")
```

```{r}
trial_data_coded <- trial_data_filtered |> recode_trials()

# exclude items that are marked for exclusion
exclusions <- redivis$organization("levante")$dataset("levante_metadata_items:czjv")$table("exclusions:0b5t")$to_tibble()
trial_data_included <- trial_data_coded |> anti_join(exclusions)
```

```{r}
task_data_nested <- trial_data_included |>
  nest(data = -c(item_task, site, language))

write_rds(task_data_nested, here("01_fetched_data/task_data_nested.rds"),
          compress = "gz")
```
