---
title: "LEVANTE Tasks - sample size report"
author: "Fionnuala O'Reilly"
toc: true
number-sections: true
highlight-style: pygments
format:
  html: 
    code-fold: true
---

Packages

```{r}

#| echo: false



library("tidyverse")
library("glue")
library("here")
library("viridis")
library("purrr")
library("readr")
library("dplyr")
library("tidyr")

```

Helper functions

```{r}

#| echo: false

source(here("02_score_data","irt_helpers.R"))
source(here("03_summaries", "plotting_helper.R"))
source(here("03_explore_tasks/explore_helper.R"))
```

Getting overall counts.


```{r}
runs <- read_rds(here("01_fetched_data/run_data.rds")) 

# Get the number of unique participants per site
n_participants <- runs |>
  distinct(site, user_id) |>
  count(site, name = "n_participants")
```


Getting counts per task per site

```{r}
# Function
summarise_task_participants <- function(task_name) {
  task_data <- load_task_data(task_name)
  
  task_summary <- task_data |>
    distinct(site, user_id) |>
    count(site, name = "n_participants") |>
    mutate(task = task_name)
  
  return(task_summary)
}

egma_summary <- summarise_task_participants("egma-math")
vocab_summary <- summarise_task_participants("vocab")
trog_summary <- summarise_task_participants("trog")
mrot_summary <- summarise_task_participants("mental-rotation")
tom_summary  <- summarise_task_participants("theory-of-mind")
mr_summary   <- summarise_task_participants("matrix-reasoning")
hf_summary   <- summarise_task_participants("hearts-and-flowers")
mg_summary   <- summarise_task_participants("memory-game")
sds_summary  <- summarise_task_participants("same-different-selection")

```

Combine into table

```{r}
all_summaries <- bind_rows(
  egma_summary, vocab_summary, trog_summary, mrot_summary, tom_summary,
  mr_summary, hf_summary, mg_summary, sds_summary
)
print(all_summaries)

# Group by site
all_summaries_by_site <- all_summaries |>
  arrange(site, task)
# print(all_summaries_by_site)
knitr::kable(all_summaries_by_site)


```


```{r}

# Group by site
wide_summaries_by_site <- all_summaries |>
  pivot_wider(names_from = "site", values_from = "n_participants", 
              values_fill = 0) |>
  arrange(task)

knitr::kable(wide_summaries_by_site)


```

# Survey counts

```{r}
surveys <- read_rds(here("01_fetched_data","survey_data_nested.rds"))
```

```{r}
surveys |>
  unnest(data) |>
  select(survey_type, site, user_id) |>
  distinct() |>
  group_by(survey_type, site) |>
  count()  |>
  pivot_wider(names_from = "site", values_from = "n") |>
  knitr::kable()
  


```


