Packages

```{r}
#| echo: false

load_or_install <- function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  }
}

load_or_install("tidyverse")
load_or_install("glue")
load_or_install("here")
load_or_install("purrr")
load_or_install("readr")
load_or_install("dplyr")
load_or_install("tidyr")
load_or_install("quarto")
load_or_install("ggthemes")
load_or_install("GGally")
load_or_install("stringr")

```

Helper functions

```{r}
#| echo: false

source(here("02_score_data","irt_helpers.R"))
source(here::here("plot_settings.R"))
source(here("03_explore_tasks/explore_helper.R"))

```

Get mental rotation data

```{r}
mr <- load_task_data("matrix-reasoning")
mr

```


Load multigroup models


```{r}

best_multigroup <- readRDS(here("02_scoring_outputs", "irt_outputs", "item_coefs.rds"))
multigroup_scores <- readRDS(here("02_scoring_outputs", "scores", "scores_multigroup.rds"))


#previous
#best_multigroup <- readRDS(here("02_scored_data", "irt_outputs", "multigroup_best_outputs.rds")) 
#multigroup_scores <- readRDS(here("02_scored_data", "scores", "scores_multigroup.rds"))
```

# Sum scores

```{r}
mr_runs <- mr |>
  group_by(site, user_id, run_id) |>
  summarise(correct = mean(correct), 
            age = mean(age),
            .groups = "drop")


mr_sum_scores <- mr_runs |> 
  filter(age < 13) |>
  ggplot(aes(x = age, y = correct)) + 
  geom_point(alpha = .5) + 
  geom_smooth(method = "gam", formula = y ~ s(x)) +
  ylim(0, 1) +
  facet_wrap(~site) + 
  labs(
    title = "Age-related accuracy, smoothed trends by site",
    x = "Age (years)",
    y = "Proportion correct",
    caption = "Note: Each point represents a participant run; smoothed trend by site"
  )

# Save the plot
ggsave(
  filename = here::here("03_explore_tasks", "Graphs", "mr_sum_scores.png"),
  plot = mr_sum_scores,
  width = 10,
  height = 6,
  dpi = 300
)

```
Let's look at dates on these. 

```{r}
colnames(mr)
mr_runs <- mr |>
  group_by(site, user_id, run_id) |>
  summarise(correct = mean(correct), 
            age = mean(age), 
            date = min(timestamp))

mr_runs |> filter(age < 13) |>
  ggplot(aes(x = age, y = correct, col = date)) + 
  geom_point(alpha = .5) + 
  geom_smooth(method = "loess", lambda = 1) +
  facet_wrap(~ site)
```

# Response Times

Median correct RT vs. number correct

```{r}
med_rt <- mr |> #filter(correct==1) |>
  mutate(rt = as.numeric(rt)) |>
  group_by(site, user_id, run_id, correct) |>
  summarise(n=n(),
            median_rt = median(rt, na.rm=T))

mr_rt_plot <- med_rt |>
  ggplot(aes(x=n, y=median_rt)) + 
  geom_point(alpha = .5) + 
  geom_smooth(method = "loess", lambda = 1) +
  facet_grid(correct ~ site) +
  labs(
  title = "Response time patterns by accuracy and site",
  subtitle = "Median RT by number of trials, separated by correct vs incorrect responses",
  x = "Number of trials (per user-run)",
  y = "Median response time (ms)",
  caption = "Each point represents a unique user-run; smoothed trend by site and accuracy"
)

ggsave(
  filename = here::here("03_explore_tasks", "Graphs", "mr_rt_plot.png"),
  plot = mr_rt_plot,
  width = 10,
  height = 6,
  dpi = 300
)


```

Median correct RT per problem: 

```{r}
med_rt |> group_by(correct) |> summarise(mean_median_rt = mean(median_rt))
```

But notice there is huge variation per child (and presumably per problem).

# IRT approach

```{r}
run_ages <- mr |>
  select(site, run_id, user_id, age) |>
  distinct()

multigroup_scores_mr <- multigroup_scores |>
  filter(task_id == "matrix-reasoning") |>
  select(site, task_id, user_id, run_id, metric_type, metric_value ) |>
  left_join(run_ages)

mr_irt <- ggplot(multigroup_scores_mr, aes(x = age, y = metric_value, col = site)) + 
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "gam", se = TRUE) +
  labs(
    title = "Developmental trends in reasoning ability by site",
    subtitle = "IRT-based theta estimates smoothed with GAM",
    x = "Age (years)",
    y = "Ability (IRT Theta Score)",
    colour = "Site"
  )

ggsave(
  filename = here::here("03_explore_tasks", "Graphs", "mr_irt.png"),
  plot = mr_irt,
  width = 10,
  height = 6,
  dpi = 300
)

```

Look at coefficients. 

```{r fig.height = 12, fig.width = 8}
mr_coefs <- best_multigroup |>
  filter(task_id == "matrix-reasoning", term == "difficulty") |>
  mutate(item = fct_reorder(item, value))
  
ggplot(mr_coefs, aes(x = item, y = -value)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Matrix Reasoning: itme difficulties (IRT)",
    x = "Item",
    y = "Difficulty (–IRT estimate)"
  )  
```

```{r}
mr_wide <- mr_coefs |>
  select(site, item, value) |>
  group_by(item, site) |>
  summarise(value = mean(value, na.rm = TRUE), .groups = "drop") |>
  pivot_wider(names_from = site, values_from = value)

GGally::ggpairs(mr_wide, columns = c("ca_pilot", "co_pilot", "de_pilot"))

```
