---
title: "Measuring the development of mental rotation ages 5-12 across three populations"
shorttitle: "LEVANTE Mental Rotation"

author: 
  - name: "Fionnuala O'Reilly*"
    orcid: 0000-0002-4355-9088
    affiliations:
      - ref: stanford
  - name: "Xingyao Xiao"
    affiliations:
      - ref: stanford
  - name: "Rebecca Zhu"
    affiliations:
      - ref: stanford
  - name: "Mika Braginsky"
    orcid: 0000-0001-9039-3220
    affiliations:
      - ref: stanford
  - name: "Nilàm Ram"
    affiliations:
      - ref: stanford
  - name: "Benjamin W. Domingue"
    affiliations:
      - ref: stanford
  - name: "Michael C. Frank"
    orcid: 0000-0002-7551-4378
    affiliations:
      - ref: stanford
    corresponding: true
    email: mcfrank@stanford.edu
    # role:
    #   - conceptualization
    #   - writing
    #   - editing
    #   - supervision

affiliations:
  - id: stanford
    name: "Stanford University"

author-note:
  disclosures:
    financial-support: "This work was supported by the Jacobs Foundation."
    # conflict-of-interest: The author has no conflict of interest to declare.

abstract: To add.

keywords: ["cognitive development", "mental rotation", "spatial reasoning"]
word-count: true

bibliography: library_mrot.bib

floatsintext: true
numbered-lines: true
# draft: false
mask: false

# appendix
number-sections: false
appendix-style: default

# figurelist: no
# tablelist: no
# footnotelist: no

format:
  apaquarto-pdf:
    documentmode: man
    keep-tex: true
    include-in-header: preamble.tex
    fig-format: pdf
    # fig-pos: H        
    # tbl-pos: H  

knitr:
  opts_chunk:
    ft.arraystretch: 1.25

execute: 
  echo: false
  message: false
  warning: false
  error: true
  cache: true
---

Spatial reasoning, broadly defined as the ability to generate, retain, and manipulate visuospatial information is a fundamental cognitive skill [@lohman2013spatial]. It allows us to form and transform mental images of 2D shapes and 3D objects (e.g., by rotating, bending, or folding them), and to represent how spatial relations between locations, shapes, and objects change over time [@frick2014development; @newcombe2014thinking].

Spatial ability is important for a wide range of educational outcomes [@wai2018spatial], including creative domains such as music [@padulo2020effects; @hetland2000learning] and visual arts [@kell2013creativity; @winner2013relationship] as well as STEM subjects [@wai2009spatial] and, most notably, math (@atit2022examining; @xie2020spatial; @mix2012relation; @gunderson2012relation]. Given it’s importance for educational outcomes, a number of attempts have been made to train spatial reasoning skills. For example, @Hhawes2015effects reported that, compared with an active control group, 6–8-year-old children who received mental rotation training showed significant gains on two separate 2D mental rotation measures, as well as more general improvements in spatial reasoning on an untrained spatial task. @uttal2013malleability conducted a meta-analysis of 217 studies with child and adult samples to examine the size and generalizability of spatial skills training effects. Across studies, the mean effect size for training compared with control conditions was Hedges’ g = 0.47 (SE = 0.04). @gilligan2020first showed that training spatial reasoning skills had	near,	intermediate	and	far	transfer	effects in 8-year old children [@gilligan2020first]. Similarly,in a sample of elementary school students, @lowrie2017visuospatial showed that those who participated in a 10-week visuospatial reasoning (VSR) program achieved substantially higher spatial reasoning scores than students in the control group, and also demonstrated improved mathematics performance.  	

```{r}






```