---
title: "HA"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(glue)
library(lavaan)
library(tidySEM)
library(ggthemes)
library(tidyr)
library(knitr)

source(here("02_score_data","irt_helpers.R"))
source(here("03_summaries", "plotting_helper.R"))
source(here("03_explore_tasks/explore_helper.R"))
```

### load thetas for 9 core tasks (not ROAR, mefs or ha)

```{r}
scores <- read_rds(here("02_scoring_outputs","scores",
                             "scores_combined.rds"))
colnames(scores)
glimpse(scores)
unique(scores$item_task)

```

```{r}
# keep only the 'ha' task
ha <- scores |>
  filter(item_task == "ha")

# Plot HA (hostile attribution) the same way as TOM
ha_irt <- ggplot(ha, aes(x = age, y = metric_value, col = site)) + 
  geom_point() + 
  geom_smooth() +
  labs(
    title = "Developmental trends in Hostile Attribution ability by site",
    subtitle = "IRT-based theta estimates smoothed with GAM",
    x = "Age (years)",
    y = "Ability (IRT Theta Score)",
    colour = "Site"
  )

print(ha_irt)



```