```{r}
source("germany/scripts/_setup.R")

de_results <- read_rds("germany/task_analyses/data/task_results.rds")
load("colombia/stage2/task_analyses/data/irt_models.RData")
co_results <- task_results
```

```{r}
de_coefs <- de_results |>
  select(task_id, dims = model_type, params = item_type, coefs) |>
  unnest(coefs) |>
  select(-g, -u) |>
  pivot_longer(cols = -c(task_id, dims, params, item),
               names_to = "term", values_to = "value") |>
  filter(!is.na(value))

co_coefs <- co_results |>
  select(task_id, dims = model_type, params = item_type, coefs) |>
  unnest(coefs) |>
  select(-g, -u) |>
  pivot_longer(cols = -c(task_id, dims, params, item),
               names_to = "term", values_to = "value") |>
  filter(!is.na(value))

all_coefs <- full_join(de_coefs, co_coefs, suffix = c("_de", "_co"),
                       by = c("task_id", "dims", "params", "item", "term"))

coef_cors <- all_coefs |>
  group_by(task_id, dims, params, term) |>
  summarise(coef_cor = cor(value_de, value_co, use = "na.or.complete"))
```
